neighbor 179.41.43.43 {
    description 'PROV1--BIRM';
    router-id 41.154.0.1;
    local-address 179.41.43.41;
    local-as 41;
    peer-as 43;
    family {
         ipv4 unicast;
    }
    static {
         route 41.0.0.0/8 next-hop self;
    }
}
neighbor 179.42.43.43 {
    description 'PROV2--FRAN';
    router-id 42.154.0.1;
    local-address 179.42.43.42;
    local-as 42;
    peer-as 43;
    family {
         ipv4 unicast;
    }
    static {
         route 42.0.0.0/8 next-hop self;
    }
}
neighbor 179.43.45.43 {
    description 'CUST1--BARC';
    router-id 45.151.0.1;
    local-address 179.43.45.45;
    local-as 45;
    peer-as 43;
    family {
         ipv4 unicast;
    }
    static {
         route 45.0.0.0/8 next-hop self;
    }
}
neighbor 179.43.46.43 {
    description 'CUST2--NAPL';
    router-id 46.151.0.1;
    local-address 179.43.46.46;
    local-as 46;
    peer-as 43;
    family {
         ipv4 unicast;
    }
    static {
         route 46.0.0.0/8 next-hop self;
    }
}
neighbor 179.43.44.43 {
    description 'PEER1--MUNI';
    router-id 44.153.0.1;
    local-address 179.43.44.44;
    local-as 44;
    peer-as 43;
    family {
         ipv4 unicast;
    }
    static {
         route 44.0.0.0/8 next-hop self;
    }
}
neighbor 180.143.0.43 {
    description 'IXP--LYON';
    router-id 180.80.143.0;
    local-address 180.143.0.143;
    local-as 143;
    peer-as 43;
    family {
         ipv4 unicast;
    }
}
