Building configuration...

Current configuration:
!
frr version 9.1
frr defaults traditional
hostname CHI_router
!
ip route 14.0.0.0/8 Null0
!
interface host
 ip address 14.105.0.2/24
exit
!
interface ixp_143
 ip address 180.143.0.14/24
exit
!
interface lo
 ip address 14.155.0.1/24
exit
!
interface port_HOU
 ip address 14.0.6.1/24
exit
!
interface port_MSP
 ip address 14.0.2.2/24
exit
!
interface port_PHY
 ip address 14.0.7.1/24
exit
!
router bgp 14
 neighbor 14.151.0.1 remote-as 14
 neighbor 14.151.0.1 update-source lo
 neighbor 14.152.0.1 remote-as 14
 neighbor 14.152.0.1 update-source lo
 neighbor 14.153.0.1 remote-as 14
 neighbor 14.153.0.1 update-source lo
 neighbor 14.154.0.1 remote-as 14
 neighbor 14.154.0.1 update-source lo
 neighbor 14.156.0.1 remote-as 14
 neighbor 14.156.0.1 update-source lo
 neighbor 14.157.0.1 remote-as 14
 neighbor 14.157.0.1 update-source lo
 neighbor 14.158.0.1 remote-as 14
 neighbor 14.158.0.1 update-source lo
 neighbor 180.143.0.143 remote-as 143
 !
 address-family ipv4 unicast
  network 14.0.0.0/8
  neighbor 14.151.0.1 next-hop-self
  neighbor 14.152.0.1 next-hop-self
  neighbor 14.153.0.1 next-hop-self
  neighbor 14.154.0.1 next-hop-self
  neighbor 14.156.0.1 next-hop-self
  neighbor 14.157.0.1 next-hop-self
  neighbor 14.158.0.1 next-hop-self
  neighbor 180.143.0.143 route-map MAP_IN_143 in
  neighbor 180.143.0.143 route-map TO_PEER out
 exit-address-family
exit
!
router ospf
 ospf router-id 14.155.0.1
 network 14.0.2.0/24 area 0
 network 14.0.6.0/24 area 0
 network 14.0.7.0/24 area 0
 network 14.105.0.0/24 area 0
 network 14.155.0.0/24 area 0
exit
!
ip prefix-list OWN_PREFIX seq 5 permit 14.0.0.0/8
!
bgp as-path access-list SAME_REGION seq 5 permit _12($|_)
bgp as-path access-list SAME_REGION seq 10 permit _16($|_)
bgp as-path access-list SAME_REGION seq 15 permit _18($|_)
bgp as-path access-list SAME_REGION seq 20 permit _20($|_)
!
bgp community-list 1 seq 5 permit 14:1
bgp community-list 2 seq 5 permit 14:2
bgp community-list 3 seq 5 permit 14:3
!
route-map ACCEPT_ALL permit 10
exit
!
route-map MAP_IN_143 deny 5
 match as-path SAME_REGION
exit
!
route-map MAP_IN_143 permit 10
 match rpki valid
 set community 14:2
 set local-preference 160
exit
!
route-map MAP_IN_143 permit 20
 match rpki notfound
 set community 14:2
 set local-preference 150
exit
!
route-map MAP_IN_143 deny 30
 match rpki invalid
exit
!
route-map TO_PEER permit 10
 match ip address prefix-list OWN_PREFIX
 set community 143:21 143:23 143:25 143:27 143:29
exit
!
route-map TO_PEER permit 20
 match community 3
 set community 143:21 143:23 143:25 143:27 143:29
exit
!
rpki
 rpki polling_period 60
 rpki cache 14.104.0.1 3323 preference 1
exit
!
end
